### ISSUE TITLE
Subscription events do not contain the stringified UUID

### ISSUE THREAD

**Issue by swilgosz** [yousty/event_store_client#38]
### Overview

When we read events from the EventStoreDB via subscription mechanism those events have `UUID` field being the type of `Structured`, while the `STRING` part is empty. If we do the same by reading normally from a stream, the String part of the UUID is present.

For the moment I've implemented a workaround to generate the random ID of events in case the STRING is empty, but it's not a proper solution.

It can generate duplicate linked events. 

### Notes

- We do use the resolve linktos for subscriptions
- We subscribe to specific event type projection, not the $all stream, so system events should not be considered.

### Steps to reproduce

1. Prepare the correct configuration
    ```ruby
    #!/usr/bin/env ruby
    
    require 'bundler/setup'
    require 'event_store_client'
    
    # Event definition
    require 'event_store_client/deserialized_event'
    
    class SomethingHappened < EventStoreClient::DeserializedEvent
      def schema
        Dry::Schema.Params do
          required(:user_id).value(:string)
          required(:title).value(:string)
        end
      end
    end
    
    # ESC configuration
    EventStoreClient.configure do |config|
      config.eventstore_url = 'https://eventstoredb:2113'
      config.adapter = :grpc
      config.verify_ssl = false
      config.eventstore_user = 'admin'
      config.eventstore_password = 'changeit'
    end
    
    stream = 'newstream'
    client = EventStoreClient::Client.new

     credentials = Base64.encode64("#{config.eventstore_user}:#{config.eventstore_password}")
     metadata = { 'authorization' => "Basic #{credentials.delete("\n")}" }
    ```
2. Publish sample events
    ```ruby
    # Publish 2 events
    events = Array.new(count) do
      SomethingHappened.new(
        data: { user_id: SecureRandom.uuid, title: 'Something happened' }
      )
    end
    client.publish(stream: stream, events: events)
    ```
3. Read the stream using raw GRPC generated stream reading functions.
    ```ruby
    # read the stream
    opts = {
      stream: { start: {}, stream_identifier: { streamName: stream } },
      read_direction: 'forwards',
      resolve_links: true,
      count: 20,
      uuid_option: { string: {} },
      no_filter: {}
    }
    request = EventStore::Client::Streams::ReadReq.new(options: opts)
    raw_events = 
      service.read(request.new(options: opts), metadata: metadata).map do |res|
        res.event.event
      end
    
    raw_events.each { |event| pp event.id.string }
    ```
    This will return events with the IDs of the String type present.

4. Read the events using the subscription mechanism.

    ```ruby
    # define the handler class
    class FooHandler
      def self.call(event)
        puts "Handled #{event.metadata['type']} with id: #{event.id.string} by FooHandler"
      end
    end

    # create a subscription for "SomethingHappened" event type
    subscription = EventStoreClient::Subscription.new(
        handler, event_types: event_types, service: 'test-service'
      )
    client.subscribe_to_stream(subscription)

    client.listen(wait: true)
    ```
This will return events with the EMPTY string in place of ids.

### What we could do with it

1. Double check if there is not issue on the server
2. Double check if creating subscriptions + consuming feeds is implemented the correct way.
3. Add a support for Structured UUIDs for events ?

**Comment by the-mikedavis** [comment]
hello! :wave:

I ran into this same odd behavior implementing subscriptions in our Elixir gRPC client [`NFIBrokerage/spear`](https://github.com/NFIBrokerage/spear).

I think what the protos call a structured UUID is just a more compressed encoding for a UUID. You can fully describe a UUID (usually a 288-bit string) with two 64 bit integers. Seems to me like object oriented languages like encoding UUIDs this way because you only need to store the `most_significant_bits` and `least_significant_bits` and then you can lazily make the normal-looking UUID string with the `toString` method.

For example, Java's [`java.util.UUID` constructor](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/UUID.html#%3Cinit%3E(long,long)) looks like

```java
public UUID(long mostSigBits, long leastSigBits)
```

and the implementation for the `toString` method is like so

```java
public String toString() {
    return (digits(mostSigBits >> 32, 8) + "-" +
            digits(mostSigBits >> 16, 4) + "-" +
            digits(mostSigBits, 4) + "-" +
            digits(leastSigBits >> 48, 4) + "-" +
            digits(leastSigBits, 12));
}

private static String digits(long val, int digits) {
    long hi = 1L << (digits * 4);
    return Long.toHexString(hi | (val & (hi - 1))).substring(1);
}
```

In Spear, we just map the structured UUIDs to the normal-looking string format. I don't really see any utility in keeping them in the super-compressed format.

For reference, here's Spear's translation of the java: https://github.com/NFIBrokerage/spear/blob/b3ce04b095abcf3d894251408ce050df34cabf0f/lib/spear/uuid.ex#L28-L78

Sadly my ruby chops are in a sorry state or else I'd love to help implement this! :)
